### ISSUE TITLE
Value of type 'NSLayoutManager' has no member 'setNeedsLayout'

### ISSUE THREAD

**Issue by fukemy** [Cocoanetics/Swift-Examples#3]
hi, can you help, this error appear in class AsyncTextAttachment
![Screen Shot 2020-06-12 at 17 19 57](https://user-images.githubusercontent.com/8202437/84492838-fca3f500-acd0-11ea-830e-592626d8a884.png)

**Comment by odrobnik** [comment]
You are missing the extensions for NSLayoutManager: https://github.com/Cocoanetics/Swift-Examples/tree/master/Attachments/Attachments
